2020-06-17 09:57:32,457    ERROR -- MainProcess google_auth.py:46 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 09:57:32,457    ERROR -- MainProcess webserver.py:79 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 09:57:33,473    INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-17 09:57:36,998    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:36] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-17 09:57:37,051    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:37] "[37mGET /static/cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 09:57:37,664    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:37] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 09:57:37,668    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:37] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 09:57:37,677    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:37] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 09:57:37,704    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:37] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,403    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,479    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1I90i HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,527    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /sw.js HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,765    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,893    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 09:57:38,893    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 09:57:38,894    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,918    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 09:57:38,943    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:38] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-17 09:57:39,096    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:39] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=b0d24df2897b4871b4cb3ee5beab24e0 HTTP/1.1[0m" 500 -
2020-06-17 09:57:39,136    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 09:57:39,532    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:57:39] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 09:58:04,097    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:58:04] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1IFJU&sid=b0d24df2897b4871b4cb3ee5beab24e0 HTTP/1.1[0m" 200 -
2020-06-17 09:58:39,101    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:58:39] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1I9Ct&sid=b0d24df2897b4871b4cb3ee5beab24e0 HTTP/1.1[0m" 400 -
2020-06-17 09:58:39,719    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:58:39] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1IO03&sid=b0d24df2897b4871b4cb3ee5beab24e0 HTTP/1.1[0m" 400 -
2020-06-17 09:58:40,126    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:58:40] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1IOC4 HTTP/1.1[0m" 200 -
2020-06-17 09:58:40,739    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:58:40] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=f416536bf30f4f099016e0d482b644d1 HTTP/1.1[0m" 500 -
2020-06-17 09:58:40,741    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 09:59:05,738    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:59:05] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1IUMg&sid=f416536bf30f4f099016e0d482b644d1 HTTP/1.1[0m" 200 -
2020-06-17 09:59:40,490    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:59:40] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1IOG2&sid=f416536bf30f4f099016e0d482b644d1 HTTP/1.1[0m" 400 -
2020-06-17 09:59:41,105    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:59:41] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Ic_D&sid=f416536bf30f4f099016e0d482b644d1 HTTP/1.1[0m" 400 -
2020-06-17 09:59:41,737    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:59:41] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1IdG9 HTTP/1.1[0m" 200 -
2020-06-17 09:59:42,352    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 09:59:42] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=c16b38513fa04518b838ec873e5c17a5 HTTP/1.1[0m" 500 -
2020-06-17 09:59:42,354    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:00:07,349    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:00:07] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1IjPK&sid=c16b38513fa04518b838ec873e5c17a5 HTTP/1.1[0m" 200 -
2020-06-17 10:00:42,357    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:00:42] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1IdIj&sid=c16b38513fa04518b838ec873e5c17a5 HTTP/1.1[0m" 400 -
2020-06-17 10:00:42,972    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:00:42] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Is5u&sid=c16b38513fa04518b838ec873e5c17a5 HTTP/1.1[0m" 400 -
2020-06-17 10:00:44,019    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:00:44] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1IsTH HTTP/1.1[0m" 200 -
2020-06-17 10:00:44,634    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:00:44] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=b546904076ec416185482ccb045bd541 HTTP/1.1[0m" 500 -
2020-06-17 10:00:44,636    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:01:09,630    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:01:09] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1IycU&sid=b546904076ec416185482ccb045bd541 HTTP/1.1[0m" 200 -
2020-06-17 10:01:44,639    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:01:44] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1IsVt&sid=b546904076ec416185482ccb045bd541 HTTP/1.1[0m" 400 -
2020-06-17 10:01:45,257    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:01:45] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1J5J3&sid=b546904076ec416185482ccb045bd541 HTTP/1.1[0m" 400 -
2020-06-17 10:01:46,081    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:01:46] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1J5c- HTTP/1.1[0m" 200 -
2020-06-17 10:01:46,699    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:01:46] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=d6e8958a9bee4803ac2edc3b711dd322 HTTP/1.1[0m" 500 -
2020-06-17 10:01:46,702    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:02:11,694    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:02:11] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1JBmE&sid=d6e8958a9bee4803ac2edc3b711dd322 HTTP/1.1[0m" 200 -
2020-06-17 10:02:46,705    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:02:46] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1J5fe&sid=d6e8958a9bee4803ac2edc3b711dd322 HTTP/1.1[0m" 400 -
2020-06-17 10:02:47,488    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:02:47] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1JKVP&sid=d6e8958a9bee4803ac2edc3b711dd322 HTTP/1.1[0m" 400 -
2020-06-17 10:02:49,044    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:02:49] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1JK-f HTTP/1.1[0m" 200 -
2020-06-17 10:02:49,661    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:02:49] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=5d3b700b83fa4a9192b8a4f15fd80447 HTTP/1.1[0m" 500 -
2020-06-17 10:02:49,666    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:03:15,482    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:03:15] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1JRKv&sid=5d3b700b83fa4a9192b8a4f15fd80447 HTTP/1.1[0m" 200 -
2020-06-17 10:03:49,665    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:03:49] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1JL1Q&sid=5d3b700b83fa4a9192b8a4f15fd80447 HTTP/1.1[0m" 400 -
2020-06-17 10:03:50,486    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:03:50] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1JZtn&sid=5d3b700b83fa4a9192b8a4f15fd80447 HTTP/1.1[0m" 400 -
2020-06-17 10:03:51,038    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:03:51] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Ja7P HTTP/1.1[0m" 200 -
2020-06-17 10:03:51,653    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:03:51] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=95807308b6484c8e8a468ca088fdb7d3 HTTP/1.1[0m" 500 -
2020-06-17 10:03:51,656    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:04:17,481    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:04:17] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1JgTe&sid=95807308b6484c8e8a468ca088fdb7d3 HTTP/1.1[0m" 200 -
2020-06-17 10:04:51,659    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:04:51] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1JaA1&sid=95807308b6484c8e8a468ca088fdb7d3 HTTP/1.1[0m" 400 -
2020-06-17 10:04:52,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:04:52] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Jp0X&sid=95807308b6484c8e8a468ca088fdb7d3 HTTP/1.1[0m" 400 -
2020-06-17 10:04:54,036    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:04:54] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1JpVm HTTP/1.1[0m" 200 -
2020-06-17 10:04:54,651    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:04:54] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=1358134c92214fef917387eba68fae1e HTTP/1.1[0m" 500 -
2020-06-17 10:04:54,653    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:05:20,483    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:05:20] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Jvs0&sid=1358134c92214fef917387eba68fae1e HTTP/1.1[0m" 200 -
2020-06-17 10:05:54,657    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:05:54] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1JpYO&sid=1358134c92214fef917387eba68fae1e HTTP/1.1[0m" 400 -
2020-06-17 10:05:55,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:05:55] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1K2Ov&sid=1358134c92214fef917387eba68fae1e HTTP/1.1[0m" 400 -
2020-06-17 10:05:56,033    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:05:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1K2eW HTTP/1.1[0m" 200 -
2020-06-17 10:05:56,651    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:05:56] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=d533e95dc0464de19827c4c101e8b7b3 HTTP/1.1[0m" 500 -
2020-06-17 10:05:56,653    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:06:21,646    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:06:21] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1K8nj&sid=d533e95dc0464de19827c4c101e8b7b3 HTTP/1.1[0m" 200 -
2020-06-17 10:06:56,656    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:06:56] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1K2h6&sid=d533e95dc0464de19827c4c101e8b7b3 HTTP/1.1[0m" 400 -
2020-06-17 10:06:57,490    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:06:57] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1KHXf&sid=d533e95dc0464de19827c4c101e8b7b3 HTTP/1.1[0m" 400 -
2020-06-17 10:06:58,037    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:06:58] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1KHnI HTTP/1.1[0m" 200 -
2020-06-17 10:06:58,654    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:06:58] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=e1cdb7b8cd43409c9e0867b843bb748a HTTP/1.1[0m" 500 -
2020-06-17 10:06:58,658    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:07:23,652    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:07:23] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1KNwZ&sid=e1cdb7b8cd43409c9e0867b843bb748a HTTP/1.1[0m" 200 -
2020-06-17 10:07:58,655    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:07:58] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1KHp-&sid=e1cdb7b8cd43409c9e0867b843bb748a HTTP/1.1[0m" 400 -
2020-06-17 10:07:59,273    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:07:59] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1KWd4&sid=e1cdb7b8cd43409c9e0867b843bb748a HTTP/1.1[0m" 400 -
2020-06-17 10:07:59,679    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:07:59] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1KWoy HTTP/1.1[0m" 200 -
2020-06-17 10:08:00,290    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:08:00] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=aa293c56a1da4328bee7d3b9551528a4 HTTP/1.1[0m" 500 -
2020-06-17 10:08:00,293    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:08:25,291    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:08:25] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Kczg&sid=aa293c56a1da4328bee7d3b9551528a4 HTTP/1.1[0m" 200 -
2020-06-17 10:09:00,034    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:09:00] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1KWt2&sid=aa293c56a1da4328bee7d3b9551528a4 HTTP/1.1[0m" 400 -
2020-06-17 10:09:00,651    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:09:00] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Klc6&sid=aa293c56a1da4328bee7d3b9551528a4 HTTP/1.1[0m" 400 -
2020-06-17 10:09:01,469    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:09:01] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Klvs HTTP/1.1[0m" 200 -
2020-06-17 10:09:02,084    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:09:02] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=96599b20490d487bb58e9e9e647354a0 HTTP/1.1[0m" 500 -
2020-06-17 10:09:02,086    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:09:27,081    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:09:27] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Ks3A&sid=96599b20490d487bb58e9e9e647354a0 HTTP/1.1[0m" 200 -
2020-06-17 10:10:02,089    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:10:02] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1KlyZ&sid=96599b20490d487bb58e9e9e647354a0 HTTP/1.1[0m" 400 -
2020-06-17 10:10:02,704    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:10:02] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1K-li&sid=96599b20490d487bb58e9e9e647354a0 HTTP/1.1[0m" 400 -
2020-06-17 10:10:03,177    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:10:03] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1K-zh HTTP/1.1[0m" 200 -
2020-06-17 10:10:03,899    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:10:03] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=01af56c1faa44f3cb60561a6408c40a8 HTTP/1.1[0m" 500 -
2020-06-17 10:10:03,920    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:10:28,801    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:10:28] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1L57V&sid=01af56c1faa44f3cb60561a6408c40a8 HTTP/1.1[0m" 200 -
2020-06-17 10:11:03,931    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:11:03] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1K_11&sid=01af56c1faa44f3cb60561a6408c40a8 HTTP/1.1[0m" 400 -
2020-06-17 10:11:04,553    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:11:04] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1LDr_&sid=01af56c1faa44f3cb60561a6408c40a8 HTTP/1.1[0m" 400 -
2020-06-17 10:11:04,973    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:11:04] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1LE2A HTTP/1.1[0m" 200 -
2020-06-17 10:11:05,587    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:11:05] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=6bf13f9e0e834ff09ff7eea341af66dd HTTP/1.1[0m" 500 -
2020-06-17 10:11:05,593    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:11:30,588    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:11:30] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1LKCv&sid=6bf13f9e0e834ff09ff7eea341af66dd HTTP/1.1[0m" 200 -
2020-06-17 10:12:05,328    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:12:05] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1LE6J&sid=6bf13f9e0e834ff09ff7eea341af66dd HTTP/1.1[0m" 400 -
2020-06-17 10:12:05,946    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:12:05] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1LSrL&sid=6bf13f9e0e834ff09ff7eea341af66dd HTTP/1.1[0m" 400 -
2020-06-17 10:12:06,353    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:12:06] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1LT1S HTTP/1.1[0m" 200 -
2020-06-17 10:12:06,964    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:12:06] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=6608a661ed38498d81baff92a00b4294 HTTP/1.1[0m" 500 -
2020-06-17 10:12:06,967    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:12:31,966    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:12:31] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1LZBz&sid=6608a661ed38498d81baff92a00b4294 HTTP/1.1[0m" 200 -
2020-06-17 10:13:06,721    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:13:06] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1LT5M&sid=6608a661ed38498d81baff92a00b4294 HTTP/1.1[0m" 400 -
2020-06-17 10:13:07,338    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:13:07] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Lhqb&sid=6608a661ed38498d81baff92a00b4294 HTTP/1.1[0m" 400 -
2020-06-17 10:13:07,749    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:13:07] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1LhzT HTTP/1.1[0m" 200 -
2020-06-17 10:13:08,366    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:13:08] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=051b022c4e6e4ba8bcfd939d5cb09f7d HTTP/1.1[0m" 500 -
2020-06-17 10:13:08,369    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:13:33,361    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:13:33] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1LoBH&sid=051b022c4e6e4ba8bcfd939d5cb09f7d HTTP/1.1[0m" 200 -
2020-06-17 10:14:08,366    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:08] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1Li4f&sid=051b022c4e6e4ba8bcfd939d5cb09f7d HTTP/1.1[0m" 400 -
2020-06-17 10:14:08,989    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:08] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Lwtp&sid=051b022c4e6e4ba8bcfd939d5cb09f7d HTTP/1.1[0m" 400 -
2020-06-17 10:14:09,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:09] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Lx6k HTTP/1.1[0m" 200 -
2020-06-17 10:14:10,103    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:10] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=f8e678d65dbf4bcb9041231c07ba0ce0 HTTP/1.1[0m" 500 -
2020-06-17 10:14:10,106    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:14:21,832    ERROR -- MainProcess google_auth.py:46 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:14:21,833    ERROR -- MainProcess webserver.py:79 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:14:22,873    INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-17 10:14:23,373    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:23] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1L-2Z HTTP/1.1[0m" 200 -
2020-06-17 10:14:23,988    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:23] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=49757cd8a735490da6a0814bee293520 HTTP/1.1[0m" 500 -
2020-06-17 10:14:23,991    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:14:26,296    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-17 10:14:26,935    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 10:14:26,944    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 10:14:26,950    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 10:14:26,958    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-17 10:14:26,964    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:26] "[37mGET /static/cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 10:14:27,341    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:27] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1L_QU HTTP/1.1[0m" 200 -
2020-06-17 10:14:27,671    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:27] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-17 10:14:27,892    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:27] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-17 10:14:28,251    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:28] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 10:14:28,426    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 10:14:28,426    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 10:14:28,442    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:28] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 10:14:28,796    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:28] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=cf49e44b95774da58ba949f99df37517 HTTP/1.1[0m" 500 -
2020-06-17 10:14:28,807    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:14:29,072    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:29] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 10:14:29,099    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:29] "[37mGET /static/favicon-32x32.png HTTP/1.1[0m" 200 -
2020-06-17 10:14:29,708    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:29] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 10:14:35,897    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:35] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 10:14:35,903    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:35] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 10:14:53,727    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:14:53] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1M5o-&sid=cf49e44b95774da58ba949f99df37517 HTTP/1.1[0m" 200 -
2020-06-17 10:15:23,461    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:23] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1L-YH&sid=49757cd8a735490da6a0814bee293520 HTTP/1.1[0m" 400 -
2020-06-17 10:15:28,820    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:28] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1L_iY&sid=cf49e44b95774da58ba949f99df37517 HTTP/1.1[0m" 400 -
2020-06-17 10:15:29,437    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:29] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1MEWu&sid=cf49e44b95774da58ba949f99df37517 HTTP/1.1[0m" 400 -
2020-06-17 10:15:29,842    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:29] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1MEhF HTTP/1.1[0m" 200 -
2020-06-17 10:15:30,469    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:30] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=cc1584bcdaa84f00b3075ba445ad6a58 HTTP/1.1[0m" 500 -
2020-06-17 10:15:30,472    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:15:42,929    ERROR -- MainProcess google_auth.py:46 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:15:42,929    ERROR -- MainProcess webserver.py:79 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:15:43,790    INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-17 10:15:44,419    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:44] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1MHMB HTTP/1.1[0m" 200 -
2020-06-17 10:15:45,035    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:45] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=84910488e1124659bd490d85affb1c31 HTTP/1.1[0m" 500 -
2020-06-17 10:15:45,037    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:15:51,713    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:51] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-17 10:15:52,363    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:52] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 10:15:52,374    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:52] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-17 10:15:52,380    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:52] "[37mGET /static/cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 10:15:52,770    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:52] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1MKH1 HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,003    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,272    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,412    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,604    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 10:15:53,604    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 10:15:53,606    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,626    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=0b45ea67234b40e097480ed3cc3a3436 HTTP/1.1[0m" 500 -
2020-06-17 10:15:53,628    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:15:53,696    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 10:15:53,700    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:53] "[37mGET /static/favicon-32x32.png HTTP/1.1[0m" 200 -
2020-06-17 10:15:54,309    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:15:54] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 10:16:01,477    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:01] "[37mGET /api/v1/graph/temperature/room HTTP/1.1[0m" 200 -
2020-06-17 10:16:06,217    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 10:16:06,217    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 10:16:06,218    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:06] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 10:16:08,579    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:08] "[37mGET /api/v1/graph/humidity/room HTTP/1.1[0m" 200 -
2020-06-17 10:16:18,622    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:18] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1MQXT&sid=0b45ea67234b40e097480ed3cc3a3436 HTTP/1.1[0m" 200 -
2020-06-17 10:16:44,493    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:44] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1MIL3&sid=84910488e1124659bd490d85affb1c31 HTTP/1.1[0m" 400 -
2020-06-17 10:16:53,631    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:53] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1MKQy&sid=0b45ea67234b40e097480ed3cc3a3436 HTTP/1.1[0m" 400 -
2020-06-17 10:16:54,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:54] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1MZHo&sid=0b45ea67234b40e097480ed3cc3a3436 HTTP/1.1[0m" 400 -
2020-06-17 10:16:56,532    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1MZn1 HTTP/1.1[0m" 200 -
2020-06-17 10:16:57,152    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:16:57] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=09c1bb82f51640448ade06b58908a8b7 HTTP/1.1[0m" 500 -
2020-06-17 10:16:57,156    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:17:22,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:17:22] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Mg7G&sid=09c1bb82f51640448ade06b58908a8b7 HTTP/1.1[0m" 200 -
2020-06-17 10:17:57,206    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:17:57] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1MZyI&sid=09c1bb82f51640448ade06b58908a8b7 HTTP/1.1[0m" 400 -
2020-06-17 10:17:58,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:17:58] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Movn&sid=09c1bb82f51640448ade06b58908a8b7 HTTP/1.1[0m" 400 -
2020-06-17 10:18:00,046    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:18:00] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1MpP2 HTTP/1.1[0m" 200 -
2020-06-17 10:18:00,664    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:18:00] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=925ffaff3a9a4607b84ae4dac6d63743 HTTP/1.1[0m" 500 -
2020-06-17 10:18:00,667    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:18:26,488    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:18:26] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1MvlI&sid=925ffaff3a9a4607b84ae4dac6d63743 HTTP/1.1[0m" 200 -
2020-06-17 10:19:00,691    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:19:00] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1MpSF&sid=925ffaff3a9a4607b84ae4dac6d63743 HTTP/1.1[0m" 400 -
2020-06-17 10:19:01,486    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:19:01] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1N2I8&sid=925ffaff3a9a4607b84ae4dac6d63743 HTTP/1.1[0m" 400 -
2020-06-17 10:19:03,033    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:19:03] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1N2nP HTTP/1.1[0m" 200 -
2020-06-17 10:19:03,648    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:19:03] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=49da3fcec7644cd0b4a01b696a0b435f HTTP/1.1[0m" 500 -
2020-06-17 10:19:03,650    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:19:29,484    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:19:29] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1N97e&sid=49da3fcec7644cd0b4a01b696a0b435f HTTP/1.1[0m" 200 -
2020-06-17 10:20:03,670    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:20:03] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1N2qK&sid=49da3fcec7644cd0b4a01b696a0b435f HTTP/1.1[0m" 400 -
2020-06-17 10:20:04,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:20:04] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1NHgX&sid=49da3fcec7644cd0b4a01b696a0b435f HTTP/1.1[0m" 400 -
2020-06-17 10:20:06,066    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:20:06] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1NI9n HTTP/1.1[0m" 200 -
2020-06-17 10:20:06,728    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:20:06] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=b273a767ccb448559b243270c4ef8d0f HTTP/1.1[0m" 500 -
2020-06-17 10:20:06,743    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:20:32,483    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:20:32] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1NOW0&sid=b273a767ccb448559b243270c4ef8d0f HTTP/1.1[0m" 200 -
2020-06-17 10:21:06,726    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:21:06] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1NIDL&sid=b273a767ccb448559b243270c4ef8d0f HTTP/1.1[0m" 400 -
2020-06-17 10:21:07,485    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:21:07] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1NX2u&sid=b273a767ccb448559b243270c4ef8d0f HTTP/1.1[0m" 400 -
2020-06-17 10:21:09,037    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:21:09] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1NXY9 HTTP/1.1[0m" 200 -
2020-06-17 10:21:09,650    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:21:09] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=45c8477e448e407296624589298d84b5 HTTP/1.1[0m" 500 -
2020-06-17 10:21:09,652    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:21:35,481    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:21:35] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1NduO&sid=45c8477e448e407296624589298d84b5 HTTP/1.1[0m" 200 -
2020-06-17 10:22:09,674    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:22:09] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1NXb8&sid=45c8477e448e407296624589298d84b5 HTTP/1.1[0m" 400 -
2020-06-17 10:22:10,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:22:10] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1NmRH&sid=45c8477e448e407296624589298d84b5 HTTP/1.1[0m" 400 -
2020-06-17 10:22:11,037    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:22:11] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Nmgu HTTP/1.1[0m" 200 -
2020-06-17 10:22:11,651    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:22:11] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=038150986ab7437c82141fc23e2cdd3b HTTP/1.1[0m" 500 -
2020-06-17 10:22:11,654    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:22:37,483    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:22:37] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Nt19&sid=038150986ab7437c82141fc23e2cdd3b HTTP/1.1[0m" 200 -
2020-06-17 10:23:11,675    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:23:11] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1Nmju&sid=038150986ab7437c82141fc23e2cdd3b HTTP/1.1[0m" 400 -
2020-06-17 10:23:12,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:23:12] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1N_a1&sid=038150986ab7437c82141fc23e2cdd3b HTTP/1.1[0m" 400 -
2020-06-17 10:23:13,059    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:23:13] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1N_pf HTTP/1.1[0m" 200 -
2020-06-17 10:23:13,685    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:23:13] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=9dee42c674f34c438e0608a5802b1a27 HTTP/1.1[0m" 500 -
2020-06-17 10:23:13,689    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:23:39,490    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:23:39] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1O69u&sid=9dee42c674f34c438e0608a5802b1a27 HTTP/1.1[0m" 200 -
2020-06-17 10:24:13,759    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:24:13] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1N_ts&sid=9dee42c674f34c438e0608a5802b1a27 HTTP/1.1[0m" 400 -
2020-06-17 10:24:14,491    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:24:14] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1OEin&sid=9dee42c674f34c438e0608a5802b1a27 HTTP/1.1[0m" 400 -
2020-06-17 10:24:16,090    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:24:16] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1OFC1 HTTP/1.1[0m" 200 -
2020-06-17 10:24:16,770    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:24:16] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=70736b4c170843c3940c23170eef0b9c HTTP/1.1[0m" 500 -
2020-06-17 10:24:16,783    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:24:42,499    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:24:42] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1OLYI&sid=70736b4c170843c3940c23170eef0b9c HTTP/1.1[0m" 200 -
2020-06-17 10:25:16,907    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:25:16] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1OFID&sid=70736b4c170843c3940c23170eef0b9c HTTP/1.1[0m" 400 -
2020-06-17 10:25:18,533    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:25:18] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1OUKn&sid=70736b4c170843c3940c23170eef0b9c HTTP/1.1[0m" 400 -
2020-06-17 10:25:20,070    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:25:20] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1OUq1 HTTP/1.1[0m" 200 -
2020-06-17 10:25:20,772    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:25:20] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=4d471beaacc142ffb863b9f6d84bf976 HTTP/1.1[0m" 500 -
2020-06-17 10:25:20,774    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:25:46,530    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:25:46] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1ObAI&sid=4d471beaacc142ffb863b9f6d84bf976 HTTP/1.1[0m" 200 -
2020-06-17 10:26:20,990    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:26:20] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1OUxl&sid=4d471beaacc142ffb863b9f6d84bf976 HTTP/1.1[0m" 400 -
2020-06-17 10:26:22,487    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:26:22] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Ojym&sid=4d471beaacc142ffb863b9f6d84bf976 HTTP/1.1[0m" 400 -
2020-06-17 10:26:24,039    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:26:24] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1OkS1 HTTP/1.1[0m" 200 -
2020-06-17 10:26:24,653    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:26:24] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=58c6827231db432ebe7782371b1c2f04 HTTP/1.1[0m" 500 -
2020-06-17 10:26:24,656    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:26:50,483    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:26:50] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1OqoG&sid=58c6827231db432ebe7782371b1c2f04 HTTP/1.1[0m" 200 -
2020-06-17 10:27:24,676    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:24] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1OkV2&sid=58c6827231db432ebe7782371b1c2f04 HTTP/1.1[0m" 400 -
2020-06-17 10:27:25,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:25] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1OzLA&sid=58c6827231db432ebe7782371b1c2f04 HTTP/1.1[0m" 400 -
2020-06-17 10:27:26,038    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:26] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Ozap HTTP/1.1[0m" 200 -
2020-06-17 10:27:26,654    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:26] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=ce99cbb1224248e4be5409e5dae552b4 HTTP/1.1[0m" 500 -
2020-06-17 10:27:26,657    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:27:26,679    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:26] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Ozdr&sid=ce99cbb1224248e4be5409e5dae552b4 HTTP/1.1[0m" 200 -
2020-06-17 10:27:52,535    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:27:52] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1P3x2&sid=ce99cbb1224248e4be5409e5dae552b4 HTTP/1.1[0m" 200 -
2020-06-17 10:28:26,932    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:28:26] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1OznU&sid=ce99cbb1224248e4be5409e5dae552b4 HTTP/1.1[0m" 400 -
2020-06-17 10:28:28,486    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:28:28] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1PCjX&sid=ce99cbb1224248e4be5409e5dae552b4 HTTP/1.1[0m" 400 -
2020-06-17 10:28:29,029    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:28:29] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1PCz9 HTTP/1.1[0m" 200 -
2020-06-17 10:28:29,644    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:28:29] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=076bf8f0e80d42fca93ae620e8f203d7 HTTP/1.1[0m" 500 -
2020-06-17 10:28:29,647    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:28:55,484    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:28:55] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1PJJP&sid=076bf8f0e80d42fca93ae620e8f203d7 HTTP/1.1[0m" 200 -
2020-06-17 10:29:29,674    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:29:29] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1PD07&sid=076bf8f0e80d42fca93ae620e8f203d7 HTTP/1.1[0m" 400 -
2020-06-17 10:29:30,488    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:29:30] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1PRsG&sid=076bf8f0e80d42fca93ae620e8f203d7 HTTP/1.1[0m" 400 -
2020-06-17 10:29:32,034    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:29:32] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1PSLX HTTP/1.1[0m" 200 -
2020-06-17 10:29:32,650    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:29:32] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=aba99e22d5fb4383afa80329a8be0c94 HTTP/1.1[0m" 500 -
2020-06-17 10:29:32,652    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:30:53,635    ERROR -- MainProcess google_auth.py:46 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:30:53,635    ERROR -- MainProcess webserver.py:79 -- Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-06-17 10:30:54,669    INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-17 10:30:55,497    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:55] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Ple0 HTTP/1.1[0m" 200 -
2020-06-17 10:30:55,573    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:55] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,114    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=4db7da2a9345420f9c9d098a7397755a HTTP/1.1[0m" 500 -
2020-06-17 10:30:56,116    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:30:56,210    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,225    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,235    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,248    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,256    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /static/cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,615    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1PmyP HTTP/1.1[0m" 200 -
2020-06-17 10:30:56,934    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:56] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-17 10:30:57,139    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-17 10:30:57,303    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 10:30:57,479    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 10:30:57,479    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 10:30:57,481    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 10:30:57,623    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=13c482d5197c43beafe5f0b25b19af63 HTTP/1.1[0m" 500 -
2020-06-17 10:30:57,625    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:30:57,704    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 10:30:57,710    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:57] "[37mGET /static/favicon-32x32.png HTTP/1.1[0m" 200 -
2020-06-17 10:30:58,318    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:30:58] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 10:31:01,276    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:01] "[37mGET /api/v1/graph/temperature/room HTTP/1.1[0m" 200 -
2020-06-17 10:31:02,938    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:02] "[37mGET /api/v1/graph/humidity/room HTTP/1.1[0m" 200 -
2020-06-17 10:31:12,768    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:12] "[37mGET /calendar HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,414    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,423    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,429    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,463    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /js/calendar.js HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,762    ERROR -- MainProcess webserver.py:200 -- cache.appcache.html
2020-06-17 10:31:13,764    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 10:31:13,828    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:13] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Pr90 HTTP/1.1[0m" 200 -
2020-06-17 10:31:14,455    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:14] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 10:31:14,626    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:14] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=cc2934558a4c49dc82c19bfdb1ddbe70 HTTP/1.1[0m" 500 -
2020-06-17 10:31:14,629    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:31:14,643    ERROR -- MainProcess webserver.py:247 -- favicon-32x32.png
2020-06-17 10:31:14,645    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:14] "[37mGET /favicon-32x32.png HTTP/1.1[0m" 200 -
2020-06-17 10:31:14,693    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:14] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 10:31:14,697    ERROR -- MainProcess webserver.py:247 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-17 10:31:14,699    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:14] "[37mGET /favicon-16x16.png HTTP/1.1[0m" 200 -
2020-06-17 10:31:15,265    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:15] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 10:31:39,630    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:39] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1PxO8&sid=cc2934558a4c49dc82c19bfdb1ddbe70 HTTP/1.1[0m" 200 -
2020-06-17 10:31:55,537    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:55] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1Pmmg&sid=4db7da2a9345420f9c9d098a7397755a HTTP/1.1[0m" 400 -
2020-06-17 10:31:57,643    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:31:57] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1Pn84&sid=13c482d5197c43beafe5f0b25b19af63 HTTP/1.1[0m" 400 -
2020-06-17 10:32:14,149    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:32:14] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1PrHY&sid=cc2934558a4c49dc82c19bfdb1ddbe70 HTTP/1.1[0m" 400 -
2020-06-17 10:32:14,767    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:32:14] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Q3z9&sid=cc2934558a4c49dc82c19bfdb1ddbe70 HTTP/1.1[0m" 400 -
2020-06-17 10:32:15,516    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:32:15] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Q4Fv HTTP/1.1[0m" 200 -
2020-06-17 10:32:16,136    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:32:16] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=7d8463ee930c418faad884d108a54ca3 HTTP/1.1[0m" 500 -
2020-06-17 10:32:16,142    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:32:41,134    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:32:41] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1QAPA&sid=7d8463ee930c418faad884d108a54ca3 HTTP/1.1[0m" 200 -
2020-06-17 10:33:16,139    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:33:16] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1Q4IZ&sid=7d8463ee930c418faad884d108a54ca3 HTTP/1.1[0m" 400 -
2020-06-17 10:33:17,489    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:33:17] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1QJH9&sid=7d8463ee930c418faad884d108a54ca3 HTTP/1.1[0m" 400 -
2020-06-17 10:33:19,034    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:33:19] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1QJmP HTTP/1.1[0m" 200 -
2020-06-17 10:33:19,648    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:33:19] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=f5b90bbb19f34e0d978bd36d0f3cee95 HTTP/1.1[0m" 500 -
2020-06-17 10:33:19,652    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:33:44,687    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:33:44] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1QPvi&sid=f5b90bbb19f34e0d978bd36d0f3cee95 HTTP/1.1[0m" 200 -
2020-06-17 10:34:19,652    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:34:19] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1QJo-&sid=f5b90bbb19f34e0d978bd36d0f3cee95 HTTP/1.1[0m" 400 -
2020-06-17 10:34:20,269    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:34:20] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1QYc8&sid=f5b90bbb19f34e0d978bd36d0f3cee95 HTTP/1.1[0m" 400 -
2020-06-17 10:34:20,672    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:34:20] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1QYnx HTTP/1.1[0m" 200 -
2020-06-17 10:34:21,282    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:34:21] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=7987dec5d731419992df99a57c832677 HTTP/1.1[0m" 500 -
2020-06-17 10:34:21,285    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:34:46,286    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:34:46] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Qeyi&sid=7987dec5d731419992df99a57c832677 HTTP/1.1[0m" 200 -
2020-06-17 10:35:21,024    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:35:21] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1QYs5&sid=7987dec5d731419992df99a57c832677 HTTP/1.1[0m" 400 -
2020-06-17 10:35:21,640    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:35:21] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1Qnb4&sid=7987dec5d731419992df99a57c832677 HTTP/1.1[0m" 400 -
2020-06-17 10:35:22,388    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:35:22] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1Qntk HTTP/1.1[0m" 200 -
2020-06-17 10:35:23,003    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:35:23] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=ccf78d25a9f7411ea10019b25ee658ec HTTP/1.1[0m" 500 -
2020-06-17 10:35:23,005    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:35:48,001    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:35:48] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1Qu10&sid=ccf78d25a9f7411ea10019b25ee658ec HTTP/1.1[0m" 200 -
2020-06-17 10:36:23,003    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:36:23] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1QnwO&sid=ccf78d25a9f7411ea10019b25ee658ec HTTP/1.1[0m" 400 -
2020-06-17 10:36:23,623    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:36:23] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1R0jY&sid=ccf78d25a9f7411ea10019b25ee658ec HTTP/1.1[0m" 400 -
2020-06-17 10:36:24,336    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:36:24] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1R0_l HTTP/1.1[0m" 200 -
2020-06-17 10:36:24,953    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:36:24] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=e7fbbe21d41a40629c7fcd42d7ca45c9 HTTP/1.1[0m" 500 -
2020-06-17 10:36:24,955    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:36:49,950    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:36:49] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1R78z&sid=e7fbbe21d41a40629c7fcd42d7ca45c9 HTTP/1.1[0m" 200 -
2020-06-17 10:37:24,953    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:24] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1R12M&sid=e7fbbe21d41a40629c7fcd42d7ca45c9 HTTP/1.1[0m" 400 -
2020-06-17 10:37:25,570    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:25] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NB1RFrT&sid=e7fbbe21d41a40629c7fcd42d7ca45c9 HTTP/1.1[0m" 400 -
2020-06-17 10:37:25,980    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:25] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1RF_r HTTP/1.1[0m" 200 -
2020-06-17 10:37:26,594    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:26] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=a42b769299364fd7b4067cac05e718e1 HTTP/1.1[0m" 500 -
2020-06-17 10:37:26,598    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:26] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1RG5X&sid=a42b769299364fd7b4067cac05e718e1 HTTP/1.1[0m" 200 -
2020-06-17 10:37:26,599    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:37:51,602    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:37:51] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NB1RMC8&sid=a42b769299364fd7b4067cac05e718e1 HTTP/1.1[0m" 200 -
2020-06-17 10:38:09,593    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:09] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,249    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,320    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,328    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,335    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,343    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /static/cache.appcache HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,655    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /socket.io/?EIO=3&transport=polling&t=NB1RQws HTTP/1.1[0m" 200 -
2020-06-17 10:38:10,997    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:10] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-17 10:38:11,167    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:11] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-17 10:38:11,361    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:11] "[37mGET /api/v1/notifications HTTP/1.1[0m" 200 -
2020-06-17 10:38:11,472    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:11] "[35m[1mGET /socket.io/?EIO=3&transport=websocket&sid=5c3bf42960c043d5b866bc08b6fc99ec HTTP/1.1[0m" 500 -
2020-06-17 10:38:11,475    ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\server.py", line 377, in handle_request
    environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 108, in handle_get_request
    start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\Arora\AppData\Local\Programs\Python\Python37\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2020-06-17 10:38:11,525    ERROR -- MainProcess server.py:201 -- 'DayOfWeek'
2020-06-17 10:38:11,525    ERROR -- MainProcess webserver.py:327 -- 'DayOfWeek'
2020-06-17 10:38:11,527    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:11] "[37mGET /api/v1/graph/coffee/week HTTP/1.1[0m" 200 -
2020-06-17 10:38:11,657    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:11] "[37mGET /static/json/manifest.json HTTP/1.1[0m" 200 -
2020-06-17 10:38:12,270    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:12] "[37mGET /static/json/images/icons/icon-144x144.png HTTP/1.1[0m" 200 -
2020-06-17 10:38:26,850    INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [17/Jun/2020 10:38:26] "[31m[1mGET /socket.io/?EIO=3&transport=polling&t=NB1RGFB&sid=a42b769299364fd7b4067cac05e718e1 HTTP/1.1[0m" 400 -
